#!/bin/bash

# tema dark
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'

# faz a chamada para os novos mirror lists
echo -e "\n[cachyos]\nInclude = /etc/pacman.d/cachyos-mirrorlist" >>/etc/pacman.conf
echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf

# cria os arquivos de mirror list
mkdir -p /etc/pacman.d/chaotic-mirrorlist
mkdir -p /etc/pacman.d/cachyos-mirrorlist

# repo chaotic-aur
echo 'Server = https://br-mirror.chaotic.cx/$repo/$arch' >/etc/pacman.d/chaotic-mirrorlist

# repo cachyos
echo 'Server = https://cdn.cachyos.org/repo/$arch/$repo' >/etc/pacman.d/cachyos-mirrorlist
echo 'Server = https://cdn77.cachyos.org/repo/$arch/$repo' >>/etc/pacman.d/cachyos-mirrorlist
echo 'Server = https://cdn-1.cachyos.org/$arch/$repo' >>/etc/pacman.d/cachyos-mirrorlist
echo 'Server = https://mirror.cachyos.org/repo/$arch/$repo' >>/etc/pacman.d/cachyos-mirrorlist

# chave do cachyos
pacman-key --recv-keys 882DCFE48E2051D48E2562ABF3B607488DB35A47
pacman-key --lsign-key 882DCFE48E2051D48E2562ABF3B607488DB35A47

# chave do chaotic-aur
pacman-key --recv-keys 1F0716DC94015CAC77FA65B619A2282AFCA8A81E
pacman-key --lsign-key 1F0716DC94015CAC77FA65B619A2282AFCA8A81E

git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

paru -Sy $(cat ./packages)
