#!/bin/python3
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import subprocess

service = ChromeService(executable_path="/home/dragon/Downloads/chromedriver-linux64/chromedriver")
url = "https://www.horariodebrasilia.org"
def convert_month(month):
    match month:
        case "janeiro":
            return "01"
        case "fevereiro":
            return "02"
        case "março":
            return "03"
        case "abril":
            return "04"
        case "maio":
            return "05"
        case "junho":
            return "06"
        case "julho":
            return "07"
        case "agosto":
            return "08"
        case "setembro":
            return "09"
        case "outubro":
            return "10"
        case "novembro":
            return "11"
        case "dezembro":
            return "12"
        case _:
            raise Exception("No month find")
def convert_day(day):
    match day:
        case "1":
            return "01"
        case "2":
            return "02"
        case "3":
            return "03"
        case "4":
            return "04"
        case "5":
            return "05"
        case "6":
            return "06"
        case "7":
            return "07"
        case "8":
            return "08"
        case "9":
            return "09"
        case _:
            return day

def parse_day(text):
    array_text = text.split(",")
    text = array_text[1]
    array_text = text.split(" de ")
    day = array_text[0].replace(" ","")
    day = convert_day(day)
    month = convert_month(array_text[1].replace(" ",""))
    year = array_text[2].replace(" ","")
    parsed_day = f'{day},{month},{year}'
    return parsed_day
def get_time():
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Enable headless mode
    chrome_options.add_argument("--disable-gpu")  # Optional for compatibility
    chrome_options.add_argument("--no-sandbox")  # Recommended for Linux
    chrome_options.add_argument("--disable-dev-shm-usage")  # Prevent memory issues
    chrome_options.add_argument("--proxy-server=http://169.254.1.1:8080")
    driver = webdriver.Chrome(service=service, options=chrome_options)
    driver.get(url)

    hour = driver.find_element(By.CSS_SELECTOR, "#relogio")
    array_hour = hour.text.split(":")
    hora = array_hour[0]
    minuto = array_hour[1]
    segundo = array_hour[2]
    day = driver.find_element(By.CSS_SELECTOR, "#dia-topo")
    day = parse_day(day.text)
    array_day = day.split(',')
    dia = array_day[0]
    mes = array_day[1]
    ano = array_day[2]

    driver.quit()
    return mes, dia, hora, minuto, ano, segundo
def main():
    try:
        mes, dia, hora, minuto, ano, segundo = get_time()
        command = ["sudo", "date", f"{mes}{dia}{hora}{minuto}{ano}.{segundo}"]
        subprocess.run(command, text=True)
    except Exception as error:
        print("A error has been ocorred:\n", error)
    return 0
if __name__ == "__main__": main();
