#!/bin/python3
import sys
import subprocess

def main():
    #make the atualization automatically
    for i in range(len(sys.argv)):
        match sys.argv[i]:
            case '-h':
                print('automatically update the libs in pip')
                return 0
            case '--help':
                print('automatically update the libs in pip')
                return 0

    arquive='requirements.txt'
    atualizationList = subprocess.run(['pip', 'list'], stdout=open('requirements.txt', 'w'))
    subprocess.run(['cat', 'requirements.txt'])
    list=[]
    with open(arquive, 'r') as file:
        line = file.readlines()
        if line:
            list.append(line)

    newList=[]
    for linhas in list:
        for linha in linhas:
            newList.append(linha)

    with open(arquive, 'w') as file: file.write('');
    with open(arquive, 'a') as file:
        for i in range(len(newList)):
            if (i+1)%2 == 1:
                file.writelines(newList[i])

    subprocess.run(['pip', 'install', '-r', 'requirements.txt', '--upgrade'])
    subprocess.run(['rm', 'requirements.txt'])
    return 0
if __name__ == '__main__':main();
