#!/bin/bash
echo "chose the language for translate to 'pt' or 'en'"
read language
while true
do
    if [ "$language" == "pt" ]; then
        tradutor
    elif [ "$language" == "en" ]; then
        translate
    else
        echo "invalid argument: $language"
        read language
    fi
done

