#!/bin/bash
language="pt"
while true
do
    if [ "$language" == "pt" ]; then
        tradutor --clearOn
        language="en"
    elif [ "$language" == "en" ]; then
        translate --clearOn
        language="pt"
    else
        echo "invalid argument: $language"
        read language
    fi
done

